name: Update Google Sheets

on:
  push:
    branches:
      - main

jobs:
  update_sheet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Google Sheet
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.APP_SCRIPT_TOKEN }}" "https://script.google.com/macros/s/SCRIPT_ID/exec"
      env:
        APP_SCRIPT_TOKEN: ${{ secrets.APP_SCRIPT_TOKEN }}
